### ISSUE TITLE
a typo in README

### ISSUE THREAD

**Issue by qindj** [fanoframework/fano-mvc#2]
```
Clone this repository

$ git clone git@github.com:fanofamework/fano-mvc.git --recursive
```

fanofamework should be fanoframework

**Comment by zamronypj** [comment]
Fix in [71b32eb5d](https://github.com/fanoframework/fano-mvc/commit/71b32eb5d63a9a082bf87ef0765bebc9da79baf5).

Thank you for reporting it.
